{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-hardware",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-11.0.0.jar",
          "url": "frc-hardware-11.0.0.jar",
          "size": 84937,
          "sha512": "28318ef37fd6881a0a4aabd4299a124f6d1ffc86b0b1ff547efb6756818298b42ab6c4d60bf7933e44e572c312edbc799d6f5686e20fd9e8195ccccdab0c0b10",
          "sha256": "04db45c5c9bb61496f8c772eec4df3598910c7d64751897f6c40f46c17c702d0",
          "sha1": "fef75f6324853f7de6780ee504bb7fbcac07dba9",
          "md5": "141c8d599030f1a79b649e94f33d0564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "frc-runtime",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-11.0.0.jar",
          "url": "frc-hardware-11.0.0.jar",
          "size": 84937,
          "sha512": "28318ef37fd6881a0a4aabd4299a124f6d1ffc86b0b1ff547efb6756818298b42ab6c4d60bf7933e44e572c312edbc799d6f5686e20fd9e8195ccccdab0c0b10",
          "sha256": "04db45c5c9bb61496f8c772eec4df3598910c7d64751897f6c40f46c17c702d0",
          "sha1": "fef75f6324853f7de6780ee504bb7fbcac07dba9",
          "md5": "141c8d599030f1a79b649e94f33d0564"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-hardware-11.0.0-sources.jar",
          "url": "frc-hardware-11.0.0-sources.jar",
          "size": 40712,
          "sha512": "5a803f48dbf851c43ea01ff193b0bf72658f43a9a193b9dc5fc647f6cab7830685580c45bfc4b3d9dfc3ff538e8c5458acbbe2afd258cde9989127f4f9a816d6",
          "sha256": "a93c4bd34317106cf9d906a5d6c8abdf9dadd50a92c7ea7fa967c3a5ea5a2818",
          "sha1": "38d5b356f29637f08be00ea1acdb7fce2a721f16",
          "md5": "27093fbb97e8c8ba58ac7a6fe4e56737"
        }
      ]
    }
  ]
}
