{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "9.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.6.jar",
          "url": "ftc-mocks-9.3.6.jar",
          "size": 157974,
          "sha512": "39deef31c07e0cb868d0b5a0b6bd27c1d238e8fe2e432d27eb4f9faf22b877ab221b4febc2fa839fb5617b362adea9a25eb0e30f192ff905d569cff4ed460140",
          "sha256": "91179e2f43258a8ce0f0d1cd1d4ded0fd328bd71582ea88cee405999ee54706e",
          "sha1": "2090e690f930c47aae0e7c5f8e60011ac60346f6",
          "md5": "a0e352a48991a23f4ab80b485b6571ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.6.jar",
          "url": "ftc-mocks-9.3.6.jar",
          "size": 157974,
          "sha512": "39deef31c07e0cb868d0b5a0b6bd27c1d238e8fe2e432d27eb4f9faf22b877ab221b4febc2fa839fb5617b362adea9a25eb0e30f192ff905d569cff4ed460140",
          "sha256": "91179e2f43258a8ce0f0d1cd1d4ded0fd328bd71582ea88cee405999ee54706e",
          "sha1": "2090e690f930c47aae0e7c5f8e60011ac60346f6",
          "md5": "a0e352a48991a23f4ab80b485b6571ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-9.3.6-sources.jar",
          "url": "ftc-mocks-9.3.6-sources.jar",
          "size": 37765,
          "sha512": "cde06f4e507fb9da0c223cb7e2d2c695d782721358d096873ed4bffd09752f3c5303e6f8fde1af0a33de44dc9e5ee59b77f3bd47aafca9b7e8a901e6e703b8a1",
          "sha256": "759a6bc5795c707cc08102a7be5a4e85bf2713f7b1d699cbc34b36d9c168c9ed",
          "sha1": "1407beaae05ccd02502e48aac8110c3e1724622a",
          "md5": "1ef0e875d423a97d7fed8ac690c36716"
        }
      ]
    }
  ]
}
