{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.0.jar",
          "url": "ftc-hardware-9.3.0.jar",
          "size": 365382,
          "sha512": "b7f1ed175ae965d3c37e90a336b5812f875d2ee2bcd7882d8a52f3a56acf43ab5b140c33b2a1d8680cbeaf07804a5c6ed279f40eaf3d058b359abac6a2f3ea62",
          "sha256": "55c0f2ec8a5fb0122fd6633e079be1b98cab66e0f88bd103e3c75cecdc1869ca",
          "sha1": "7f865415ce1ff0f89685a33bcd730ec1e58bd7d8",
          "md5": "2de7c4993dc74fb989749af3d554fc06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.0.jar",
          "url": "ftc-hardware-9.3.0.jar",
          "size": 365382,
          "sha512": "b7f1ed175ae965d3c37e90a336b5812f875d2ee2bcd7882d8a52f3a56acf43ab5b140c33b2a1d8680cbeaf07804a5c6ed279f40eaf3d058b359abac6a2f3ea62",
          "sha256": "55c0f2ec8a5fb0122fd6633e079be1b98cab66e0f88bd103e3c75cecdc1869ca",
          "sha1": "7f865415ce1ff0f89685a33bcd730ec1e58bd7d8",
          "md5": "2de7c4993dc74fb989749af3d554fc06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.3.0-sources.jar",
          "url": "ftc-hardware-9.3.0-sources.jar",
          "size": 146580,
          "sha512": "42561f2ed86a6f5d0f75e04985abced9e0f40b482b228e4319ad7846f32cbd1f17e9f2000b638b1d37864dd8e891d68a2e48cadedf42046cbdaa8a30df69849f",
          "sha256": "8a06ee68fab31a2bc04d5b5fccb88d380623025487781e5e8a4d1ef066720e24",
          "sha1": "386113f2c0e75bbd97fb92a3c04d6c01ac1d87d2",
          "md5": "ec0d719016f5bb8342c3d479ec70d68d"
        }
      ]
    }
  ]
}
