{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.0.0.jar",
          "url": "ftc-hardware-11.0.0.jar",
          "size": 409521,
          "sha512": "5652fac363861ad64f6e36b5621a3c2f113a2a204018dbffffec8f25c348dda14db3967ff113af735021e9006ebe3cea474f65e0abff295581c3fa4f921afcf4",
          "sha256": "db45972a296fe79a996c47becc4a83cb3d890ba2db613523d817198f1299430c",
          "sha1": "f14ed21889c0c79e914213fee1e3429fe888b87a",
          "md5": "a0b679fbb82410c81f01710ff8d65fe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-11.0.0.jar",
          "url": "ftc-hardware-11.0.0.jar",
          "size": 409521,
          "sha512": "5652fac363861ad64f6e36b5621a3c2f113a2a204018dbffffec8f25c348dda14db3967ff113af735021e9006ebe3cea474f65e0abff295581c3fa4f921afcf4",
          "sha256": "db45972a296fe79a996c47becc4a83cb3d890ba2db613523d817198f1299430c",
          "sha1": "f14ed21889c0c79e914213fee1e3429fe888b87a",
          "md5": "a0b679fbb82410c81f01710ff8d65fe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-11.0.0-sources.jar",
          "url": "ftc-hardware-11.0.0-sources.jar",
          "size": 155028,
          "sha512": "01e9136b5ba461ef881d7133a5c2f65dccd3366e8918450a7512c433d5b0c637131618cd5f4d3991a8aee74b4e88933196f1d84fdb50f71786dbbc022f6d8932",
          "sha256": "54b17ec61a4e526b3afb69220fa7c27cafd227ee801fd1c3575a6a76f3672d9b",
          "sha1": "f25045cc0792aef8bac29645a54baeec3d8bb34b",
          "md5": "002d34dd03b7646418b698c45e1134df"
        }
      ]
    }
  ]
}
