{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.4.0.jar",
          "url": "simulator-runtime-linux-9.4.0.jar",
          "size": 4326,
          "sha512": "1dcdcc0f92abe643540ab744119d28e8be356baec71f9cab0c1a9492942316d6c57bd42af856da894a63bfbb386abc52ec0b0d5144e31a57ca6c6864f3cacf45",
          "sha256": "a0bf76eea1fd03bf60a6350808bb82c5886bcef0fb3fc1affdde5cae8eaed8cd",
          "sha1": "722bb7ae7eec285229ab501605fcf1bf0a491fce",
          "md5": "c3ddd79560f39f39afc10dc0e8b0a5a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.4.0.jar",
          "url": "simulator-runtime-linux-9.4.0.jar",
          "size": 4326,
          "sha512": "1dcdcc0f92abe643540ab744119d28e8be356baec71f9cab0c1a9492942316d6c57bd42af856da894a63bfbb386abc52ec0b0d5144e31a57ca6c6864f3cacf45",
          "sha256": "a0bf76eea1fd03bf60a6350808bb82c5886bcef0fb3fc1affdde5cae8eaed8cd",
          "sha1": "722bb7ae7eec285229ab501605fcf1bf0a491fce",
          "md5": "c3ddd79560f39f39afc10dc0e8b0a5a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-9.4.0-sources.jar",
          "url": "simulator-runtime-linux-9.4.0-sources.jar",
          "size": 4326,
          "sha512": "f38c168277ac392b8653a469c23473bc10f97dfe574c621a8b7a1d9021a6f0326f272a97a3dc9344a527cd29844f222d4bf2b0a4a17b758d3e91e194793fa9f3",
          "sha256": "d4b63af0d3d46b3105fef81a305881b05f7d26c0e24619633993760fe92da5d4",
          "sha1": "563a188597d9ccdb485cdc48e911b88c60938214",
          "md5": "a325b48d29457f3e94c9b17197d029f8"
        }
      ]
    }
  ]
}
