android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
aresVersion=9.9.0
mavenCentralPublishing=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -XX:+TieredCompilation -XX:TieredStopAtLevel=1
kotlin.incremental=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

POM_NAME=ARES Robotics Library
POM_DESCRIPTION=Shared Kotlin robotics, hardware, simulation, and code-generation libraries for ARES FIRST Robotics.
POM_INCEPTION_YEAR=2024
POM_URL=https://github.com/ARES-23247/ARESLib-Kotlin
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/ARES-23247/ARESLib-Kotlin
POM_SCM_CONNECTION=scm:git:https://github.com/ARES-23247/ARESLib-Kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ARES-23247/ARESLib-Kotlin.git
POM_DEVELOPER_ID=ares-first
POM_DEVELOPER_NAME=ARES FIRST Robotics
POM_DEVELOPER_EMAIL=ares23247wv@gmail.com
POM_DEVELOPER_URL=https://aresfirst.org
