{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.5.jar",
          "url": "ftc-hardware-9.3.5.jar",
          "size": 365382,
          "sha512": "55b53fc1bfd07aba14d5723bd8a263faf467579b5f8203222431ef92e6fd861fed5df0ac75f1b7613f0a3171b977ed3c396cfb55141e231409cd5b4ce3ddef17",
          "sha256": "cfa9ddea0fc371e4cdb50ee6b48a5aa72b6fbe96a643ace123cb32a8f10a43f3",
          "sha1": "b5e2a94a92afd3724b5db8f4dfa83ad71668bac4",
          "md5": "e5117b85f9cf8c0f1141a22326adbda7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.5.jar",
          "url": "ftc-hardware-9.3.5.jar",
          "size": 365382,
          "sha512": "55b53fc1bfd07aba14d5723bd8a263faf467579b5f8203222431ef92e6fd861fed5df0ac75f1b7613f0a3171b977ed3c396cfb55141e231409cd5b4ce3ddef17",
          "sha256": "cfa9ddea0fc371e4cdb50ee6b48a5aa72b6fbe96a643ace123cb32a8f10a43f3",
          "sha1": "b5e2a94a92afd3724b5db8f4dfa83ad71668bac4",
          "md5": "e5117b85f9cf8c0f1141a22326adbda7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.3.5-sources.jar",
          "url": "ftc-hardware-9.3.5-sources.jar",
          "size": 146580,
          "sha512": "5950b0563974bf7d71efa8f40f433d65c879c23063ac9385df0160fff93d9c970b31515539718a3703f90084ec73856b4542f3a8c805a5b2eb31f76f86e65d1a",
          "sha256": "376f7766d5d6e5f450fe1ca3a888769c84e86e058531d38f578cf94a748a2906",
          "sha1": "ac83400405ef4097ad91c632dab93a4075f6e0b8",
          "md5": "9009ee0537ba6dc8dd68ec72bed30b54"
        }
      ]
    }
  ]
}
