{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "9.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.3.3.jar",
          "url": "core-9.3.3.jar",
          "size": 2099744,
          "sha512": "bc2b60c3e1a87afa930be65f65fbee3a347d2f8eea0c879f3884ac3f66811e027843da8fdb54a858a7845a5d5920068d77bc3f86a035c285763a5172cbeab26f",
          "sha256": "16631725677f2a4a2cf8e9ae8e8011b164cff2624e775bf25c1cfe0c5787b1a4",
          "sha1": "ca60d1b97e6a6a225bac8ac8c128763e6485451c",
          "md5": "4ae29c4fbff410f7d5eb0c37c5f3b8f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.3.3.jar",
          "url": "core-9.3.3.jar",
          "size": 2099744,
          "sha512": "bc2b60c3e1a87afa930be65f65fbee3a347d2f8eea0c879f3884ac3f66811e027843da8fdb54a858a7845a5d5920068d77bc3f86a035c285763a5172cbeab26f",
          "sha256": "16631725677f2a4a2cf8e9ae8e8011b164cff2624e775bf25c1cfe0c5787b1a4",
          "sha1": "ca60d1b97e6a6a225bac8ac8c128763e6485451c",
          "md5": "4ae29c4fbff410f7d5eb0c37c5f3b8f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-9.3.3-sources.jar",
          "url": "core-9.3.3-sources.jar",
          "size": 547287,
          "sha512": "31d6d6c25781276a3022f3bc88a9cd092b4deff348e14f1887152eeaebb0c469b40c8a406c2e28978940c09594a3c1e4a012f31656a655b4f233099b4cd2d009",
          "sha256": "6862605182787a5b731846961f5dcc88178b79c75803257c5b659a6928fc5da1",
          "sha1": "4a0d35061474f1248c8b75ba2b57e197f9d2f99a",
          "md5": "dc3c41508b7029973e51ae6cb8bd2b62"
        }
      ]
    }
  ]
}
