{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "9.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-9.7.0.jar",
          "url": "simulator-9.7.0.jar",
          "size": 194088,
          "sha512": "a9195ef0d4f859cfb6d9ee42b29356fc411c1b9ff3be1a92be820cca74284f3a669f7141ef17fd8463e12116776192496b3e0dc7c51d79e495a3eab3eb76bd86",
          "sha256": "ef5b2687281ea996c5b8c850c28e3c4cb233db64c04f880816bede10b21a0a07",
          "sha1": "f39d9adbbfd1be2dd5c40ebb62b082fd21de8f44",
          "md5": "70967d646da6e9ff456fb5dabcd2f85f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-9.7.0.jar",
          "url": "simulator-9.7.0.jar",
          "size": 194088,
          "sha512": "a9195ef0d4f859cfb6d9ee42b29356fc411c1b9ff3be1a92be820cca74284f3a669f7141ef17fd8463e12116776192496b3e0dc7c51d79e495a3eab3eb76bd86",
          "sha256": "ef5b2687281ea996c5b8c850c28e3c4cb233db64c04f880816bede10b21a0a07",
          "sha1": "f39d9adbbfd1be2dd5c40ebb62b082fd21de8f44",
          "md5": "70967d646da6e9ff456fb5dabcd2f85f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-9.7.0-sources.jar",
          "url": "simulator-9.7.0-sources.jar",
          "size": 67879,
          "sha512": "e01c50ece47074af8e02a1b9944f6d6caa7b3280e83672a9cc0df01bbe181a799dfa2b90cfb7e6e005840e3d2bf75e19f2c2cb3189d0f651cbbb896f9d2ddeb5",
          "sha256": "1ea15ad9a3709356b8d4c84c6f21fc0f184db0c33b9e913d4a2446557f4f4256",
          "sha1": "d6a7a19398fdea37eb4aa98ece51365a626d5651",
          "md5": "3eb436c1abb38584af297e8fcd83c2bd"
        }
      ]
    }
  ]
}
