{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "9.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.10.0.jar",
          "url": "simulator-runtime-linux-9.10.0.jar",
          "size": 5085,
          "sha512": "aeeaae20dd7657ebe4a8bbec035336d8667c85eee565cacadc397ecc100ea483576896b066aefb789b5010ef0ab1ce9a8652446e70cf15f9feb9781a47c8d083",
          "sha256": "413815560233a5b6cdbcf4df297a010abd68dabb0f7a52668c7bb6458ca71872",
          "sha1": "3bd311db44cf5b3a4a733bd34af033317dd08ae1",
          "md5": "8cbf88c1f66d3495a7f44a0cc81f66e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.10.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.10.0.jar",
          "url": "simulator-runtime-linux-9.10.0.jar",
          "size": 5085,
          "sha512": "aeeaae20dd7657ebe4a8bbec035336d8667c85eee565cacadc397ecc100ea483576896b066aefb789b5010ef0ab1ce9a8652446e70cf15f9feb9781a47c8d083",
          "sha256": "413815560233a5b6cdbcf4df297a010abd68dabb0f7a52668c7bb6458ca71872",
          "sha1": "3bd311db44cf5b3a4a733bd34af033317dd08ae1",
          "md5": "8cbf88c1f66d3495a7f44a0cc81f66e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-9.10.0-sources.jar",
          "url": "simulator-runtime-linux-9.10.0-sources.jar",
          "size": 5085,
          "sha512": "7cd484de9746caa119019f87ea8b9451b51250abd73614fc20aa903957497212dccdb992a335eb56aa911e81b16b3f85f9ff70a099cb00d034061688308d38b5",
          "sha256": "926450b745014c8a08ededda4cf7c669a021510301ac27be03e061b0c507da32",
          "sha1": "194b48f21daf65189c1571d5623e804670f700d2",
          "md5": "8bfaaf476ccd4a123ffd1acce52777b1"
        }
      ]
    }
  ]
}
