{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.5.0.jar",
          "url": "core-9.5.0.jar",
          "size": 2168722,
          "sha512": "7f19a6d771f5ca8decce0eaca9cb1afa24f9d8927af484a092dafd8d0528b2d01da68cba7b5474a204db99fbbe9837ea989aac7433cd576afe9a082cd7f61e37",
          "sha256": "5077625349c088490e7205584e7444cc498c9574dc2e9c75ecb4ff59572dd56c",
          "sha1": "18e3bc6dc8da850b48070e03333e7de2d02a7921",
          "md5": "07b95152bdb81ca1e580a9142673e14f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.5.0.jar",
          "url": "core-9.5.0.jar",
          "size": 2168722,
          "sha512": "7f19a6d771f5ca8decce0eaca9cb1afa24f9d8927af484a092dafd8d0528b2d01da68cba7b5474a204db99fbbe9837ea989aac7433cd576afe9a082cd7f61e37",
          "sha256": "5077625349c088490e7205584e7444cc498c9574dc2e9c75ecb4ff59572dd56c",
          "sha1": "18e3bc6dc8da850b48070e03333e7de2d02a7921",
          "md5": "07b95152bdb81ca1e580a9142673e14f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-9.5.0-sources.jar",
          "url": "core-9.5.0-sources.jar",
          "size": 565250,
          "sha512": "a0b1fbda39e1eea15904b3d5d20740a2d0535da8c9c40880e6db83bad6e3da36904a8341b4434b16410acea73bf0e50f93072846c160cc8df88372d9fa0bebc7",
          "sha256": "aa867e411c51632516d45faedbbbadc4500d46baacda8785abbac79c0da4562d",
          "sha1": "988d229e48e2938787bb0cd813c0623a760a5091",
          "md5": "598b9c8a589235636f4b2067c59c2bc7"
        }
      ]
    }
  ]
}
