{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.0.0.jar",
          "url": "simulation-foundation-11.0.0.jar",
          "size": 35297,
          "sha512": "e52534011c88e1b02f075dce27727b34ec95b24cc29a22beeac650aafa1b23e06c655f03e8a59731baf43352104a50409425358aa0480ee00601de76be8b257c",
          "sha256": "7e231b57f5135d6db4f2d3e2f27efa030a407242739551d18d7d8f0d0d3c6f1c",
          "sha1": "a904c466c57cd9223b97d44b637027afb895a0b5",
          "md5": "a379cf59266b5be1185599be2e69f02f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-11.0.0.jar",
          "url": "simulation-foundation-11.0.0.jar",
          "size": 35297,
          "sha512": "e52534011c88e1b02f075dce27727b34ec95b24cc29a22beeac650aafa1b23e06c655f03e8a59731baf43352104a50409425358aa0480ee00601de76be8b257c",
          "sha256": "7e231b57f5135d6db4f2d3e2f27efa030a407242739551d18d7d8f0d0d3c6f1c",
          "sha1": "a904c466c57cd9223b97d44b637027afb895a0b5",
          "md5": "a379cf59266b5be1185599be2e69f02f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-11.0.0-sources.jar",
          "url": "simulation-foundation-11.0.0-sources.jar",
          "size": 8791,
          "sha512": "6a087b090605d5247a9ed7fe1ff5a87148c7b09bdfa2a421e8eede80c839107c423d36836a651205022fce524f5b8d34c69c445db36ed504ac61badef4cbb72d",
          "sha256": "63bb34aa20107c0ed70af503f192380c14db40313b49cca2c003ab3f753a4dfe",
          "sha1": "788428ade4e911092802f860f321cb3cb6e4339a",
          "md5": "e82c3d11817b27c7a01ecb69180fa98f"
        }
      ]
    }
  ]
}
