{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.4.0.jar",
          "url": "codegen-9.4.0.jar",
          "size": 279738,
          "sha512": "1bd00610c5e11a9ed99e49141b20c4069e5e368927a5f59778dd1684593f532c061f6774c3484ecd956f0699ca3f9f22453b11f8e80416edaee727084dc315b3",
          "sha256": "4f1ee31e3b72c1d9ce6a19787a9c57692af7217a4fd4bc56d83567bc0f632d18",
          "sha1": "791c17e3cc4741c5796b114db880bed31db47fb9",
          "md5": "55c2cf7e430a14babc6876e95e82557d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.4.0.jar",
          "url": "codegen-9.4.0.jar",
          "size": 279738,
          "sha512": "1bd00610c5e11a9ed99e49141b20c4069e5e368927a5f59778dd1684593f532c061f6774c3484ecd956f0699ca3f9f22453b11f8e80416edaee727084dc315b3",
          "sha256": "4f1ee31e3b72c1d9ce6a19787a9c57692af7217a4fd4bc56d83567bc0f632d18",
          "sha1": "791c17e3cc4741c5796b114db880bed31db47fb9",
          "md5": "55c2cf7e430a14babc6876e95e82557d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-9.4.0-sources.jar",
          "url": "codegen-9.4.0-sources.jar",
          "size": 559705,
          "sha512": "325a61ba0700a0fc868ab68b371eda0da5899554500c0137a654d310dfc78f2cb252a08bb0b0c4e6ac5d8881b5b47936bb246e63e4ca39d09e7b419e05f7bbcf",
          "sha256": "499e2feab04d14d6b87cf64471a1387be4ee5b8d53ef32d9da48e92cab8af9ff",
          "sha1": "9d9ee5cce14438b6b191eacdf864e22a94c0abd1",
          "md5": "77da9289ddaf485f7e28559133f55898"
        }
      ]
    }
  ]
}
