{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-10.1.0.jar",
          "url": "ftc-mocks-10.1.0.jar",
          "size": 168785,
          "sha512": "ee056e89ce1789031e5375758469d69528b0f83676741dc20a87656a6fc5a49fe5f128dc5aa4564bf676b2141b4cf2cd0b2d66347bfcd8232736b6129420160a",
          "sha256": "6b7b46c79b2a39c9719157d5ac136b1fdd7936083b17aea2df1c53d7746c518b",
          "sha1": "206065264993d36ac013e6468fc142664f1748f2",
          "md5": "8f8f169ce900c923121d52fbcc9a5e03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-10.1.0.jar",
          "url": "ftc-mocks-10.1.0.jar",
          "size": 168785,
          "sha512": "ee056e89ce1789031e5375758469d69528b0f83676741dc20a87656a6fc5a49fe5f128dc5aa4564bf676b2141b4cf2cd0b2d66347bfcd8232736b6129420160a",
          "sha256": "6b7b46c79b2a39c9719157d5ac136b1fdd7936083b17aea2df1c53d7746c518b",
          "sha1": "206065264993d36ac013e6468fc142664f1748f2",
          "md5": "8f8f169ce900c923121d52fbcc9a5e03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-10.1.0-sources.jar",
          "url": "ftc-mocks-10.1.0-sources.jar",
          "size": 39884,
          "sha512": "f3fc736f4e6dc6e5a3c8d904c7ab4c933a2ecfdd3f5003c359f7b024851f51fa80aa06ca73ea86633c3e4dc1b7f6c8cb123a97aaac858fecbeebf16d1cef40f1",
          "sha256": "0f8d0787c33b8fba49af1a9f343737bfc62aa8a20f155b458db740ced1fbd985",
          "sha1": "a888899216c785b8b8dcfa3fbfaf1f48a72290e6",
          "md5": "9d9fcf26d1d6e2c17527c60639e445e2"
        }
      ]
    }
  ]
}
