{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.5.0.jar",
          "url": "ftc-hardware-9.5.0.jar",
          "size": 365390,
          "sha512": "10c958ef0a221edcc929153e7650564faf92ddf40c8c6f7a3ab1a161d290c08e4d081f8b2ce24d2bbb0521448dc3a806a9df045965badecf4a20dec2647cbe0a",
          "sha256": "a9cc3454edae8ac4e7dc8a38a4d8b2d638d6d99c480fe479a9455f1ad9b75e20",
          "sha1": "0b98e32c4fa477ad7b8e11dc007586d118f2461d",
          "md5": "7ef3b307c85da8c8e0d3c7696a0701cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.5.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.5.0.jar",
          "url": "ftc-hardware-9.5.0.jar",
          "size": 365390,
          "sha512": "10c958ef0a221edcc929153e7650564faf92ddf40c8c6f7a3ab1a161d290c08e4d081f8b2ce24d2bbb0521448dc3a806a9df045965badecf4a20dec2647cbe0a",
          "sha256": "a9cc3454edae8ac4e7dc8a38a4d8b2d638d6d99c480fe479a9455f1ad9b75e20",
          "sha1": "0b98e32c4fa477ad7b8e11dc007586d118f2461d",
          "md5": "7ef3b307c85da8c8e0d3c7696a0701cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.5.0-sources.jar",
          "url": "ftc-hardware-9.5.0-sources.jar",
          "size": 146641,
          "sha512": "0837a95a10c667e0179cc9a1b47ce3c4db54147220a3a7a1787dc2e31a9301ff092b4d1fa56155f91829aaefb084f50568a2c6653d454e8f78b642539561cf2e",
          "sha256": "1ba94e8d7f9dd32d04338df5fcb64e72449b4e584c2cd1d35e03587ad2a55fa9",
          "sha1": "16979d5e4b5a66ce95e5b2bac4317619fd56467e",
          "md5": "6417c2c549be6c2536d1005457be2394"
        }
      ]
    }
  ]
}
