{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "9.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.9.0.jar",
          "url": "simulator-runtime-linux-9.9.0.jar",
          "size": 5085,
          "sha512": "581c86e423492ef3625d401c0e31d61babf13905dd177fa481171ec2c52e3214bf9b447d719bb41e75aaf51b30232932f688d3b34e73f58c008b07d2b69682a3",
          "sha256": "b8e9332998aa88cf8f0441173f8e787b13acf19424aae182fe2e3801111a13c3",
          "sha1": "64ccc50d71abf871d9f67a58fe2878f760fb7f5b",
          "md5": "83dc8896f7b500698cefab871da987cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.9.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.9.0.jar",
          "url": "simulator-runtime-linux-9.9.0.jar",
          "size": 5085,
          "sha512": "581c86e423492ef3625d401c0e31d61babf13905dd177fa481171ec2c52e3214bf9b447d719bb41e75aaf51b30232932f688d3b34e73f58c008b07d2b69682a3",
          "sha256": "b8e9332998aa88cf8f0441173f8e787b13acf19424aae182fe2e3801111a13c3",
          "sha1": "64ccc50d71abf871d9f67a58fe2878f760fb7f5b",
          "md5": "83dc8896f7b500698cefab871da987cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-9.9.0-sources.jar",
          "url": "simulator-runtime-linux-9.9.0-sources.jar",
          "size": 5085,
          "sha512": "0a9330c6be3bfa8398d659426013e4e0dabd7d217432e907a2fd4bffc013ab344b89b4c5bef0485504fc6c36453520a9de277a32912bd9f0958f561c0bdccd08",
          "sha256": "20cc912adab4a0d2d7da9f259f52fc74b51332abb1714d47d763bb9257fa6e57",
          "sha1": "6cc90c47152a9390f2bab523ca10e02896b780f7",
          "md5": "246ab046a0dd14ceb36a1b92ac6b446a"
        }
      ]
    }
  ]
}
