{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.6.jar",
          "url": "ftc-hardware-9.3.6.jar",
          "size": 365377,
          "sha512": "9a754aa5463f0f869342404b1575f70898e07e0c63e5743262f2525c3b1197951648410c05cf28a04430b6530c7bfdb86d6ccbd6d819fac3b674db9d65ab4fd2",
          "sha256": "eccf643a8aa1f292716099d5a606f7fb39f4f82b1ea8651f31d04cd18bd2bfc8",
          "sha1": "24b197153792076a05f1c4e74e99aa7aec7f3570",
          "md5": "502b79d1c821984e8c1ea13670d8d8cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.3.6.jar",
          "url": "ftc-hardware-9.3.6.jar",
          "size": 365377,
          "sha512": "9a754aa5463f0f869342404b1575f70898e07e0c63e5743262f2525c3b1197951648410c05cf28a04430b6530c7bfdb86d6ccbd6d819fac3b674db9d65ab4fd2",
          "sha256": "eccf643a8aa1f292716099d5a606f7fb39f4f82b1ea8651f31d04cd18bd2bfc8",
          "sha1": "24b197153792076a05f1c4e74e99aa7aec7f3570",
          "md5": "502b79d1c821984e8c1ea13670d8d8cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.3.6-sources.jar",
          "url": "ftc-hardware-9.3.6-sources.jar",
          "size": 146639,
          "sha512": "d9a7186d8b748e944d4ff64999d4e71ab10ef5843044c4132cc02c3c44a2083e23e1f1430ce5efc3a33f4d202eca0e8408740008d8e57624c95e848a512d4955",
          "sha256": "09c51d02a895a10f967ee382758024be5dc437038c739a4501d359a2dc5eb07d",
          "sha1": "3d5a00197540b7cfbfa419d35f5411adb8785378",
          "md5": "dcbf96f60cfdcdee82ed222b6c2203a3"
        }
      ]
    }
  ]
}
