{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "frc-hardware",
    "version": "9.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-9.6.0.jar",
          "url": "frc-hardware-9.6.0.jar",
          "size": 85261,
          "sha512": "dba708f601151b24d30889df732514fd2dc21cec0081152ffdddf4fbe27c9841050aed99cddde90be4c6b4dac1740b0560fd69b5c7b81e17ac466b8b35380778",
          "sha256": "d8c1f86a7230d48051ef402832c6580ee74fc025d8f92b0889edb04c0488f94e",
          "sha1": "bf245d591747338a475bfccb8059bb543d30dcb6",
          "md5": "3ffdc3ce20b5b5675455cb83d086a008"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "frc-hardware-9.6.0.jar",
          "url": "frc-hardware-9.6.0.jar",
          "size": 85261,
          "sha512": "dba708f601151b24d30889df732514fd2dc21cec0081152ffdddf4fbe27c9841050aed99cddde90be4c6b4dac1740b0560fd69b5c7b81e17ac466b8b35380778",
          "sha256": "d8c1f86a7230d48051ef402832c6580ee74fc025d8f92b0889edb04c0488f94e",
          "sha1": "bf245d591747338a475bfccb8059bb543d30dcb6",
          "md5": "3ffdc3ce20b5b5675455cb83d086a008"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "frc-hardware-9.6.0-sources.jar",
          "url": "frc-hardware-9.6.0-sources.jar",
          "size": 41933,
          "sha512": "9db7184a28196efbe31d5c60c9e9eb9b98ca904b53ceacfc2ffb4b8a390c6d41f17678ea62131e88da273fe7c49f1fc7255f0ae31b1241ae913d96fd0ff0ce9c",
          "sha256": "6f4b13381e2b8af20c77e5c58e9a8476c4767f32f87aa60eb531a9b3b4988c6e",
          "sha1": "bdaa75362a5486cf516eb2f9d3e037a528ec28ca",
          "md5": "f099f7303747d47273d7d8595a0c09fd"
        }
      ]
    }
  ]
}
