{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.4.0.jar",
          "url": "ftc-hardware-9.4.0.jar",
          "size": 365390,
          "sha512": "e0e6ca759bd8143ae14d728ec30a11d8881f9fb2b5659d6610e248153844a65ae4a340666e8aacf8a7de93e90c6a7509dca253fa03b8d3c25c5ae5815e7882e7",
          "sha256": "cb644d6299f0c5898ca8fa0acaa3fac84ee0f7e669bd86a7ce44c2199f655030",
          "sha1": "a5a8271d0a1274ff9c1ab587741780b5a7ebc1d0",
          "md5": "c1656be88ce1a985f2f940cd0da5963f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.4.0.jar",
          "url": "ftc-hardware-9.4.0.jar",
          "size": 365390,
          "sha512": "e0e6ca759bd8143ae14d728ec30a11d8881f9fb2b5659d6610e248153844a65ae4a340666e8aacf8a7de93e90c6a7509dca253fa03b8d3c25c5ae5815e7882e7",
          "sha256": "cb644d6299f0c5898ca8fa0acaa3fac84ee0f7e669bd86a7ce44c2199f655030",
          "sha1": "a5a8271d0a1274ff9c1ab587741780b5a7ebc1d0",
          "md5": "c1656be88ce1a985f2f940cd0da5963f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.4.0-sources.jar",
          "url": "ftc-hardware-9.4.0-sources.jar",
          "size": 146641,
          "sha512": "841a58f72138e27b3b93e25ac89a1ae2ae9905becdbcccf87a0c6a631fc7af45aae3be56a982f4271990a827bb6566ff4f6be57bc8d3a6be0010a041b4fba162",
          "sha256": "7d74550e6ec84e259148d7139623bd305daa046ec0149bf500fcb2ac3de3e92e",
          "sha1": "f8c6b01fc5654563cb9212d9f1a040bda3c872c0",
          "md5": "582dbb2eaf7666617b674241bf26dbb2"
        }
      ]
    }
  ]
}
