{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.1.jar",
          "url": "ftc-mocks-9.3.1.jar",
          "size": 157974,
          "sha512": "d03d07c1d6c060f1d22ee8bd489881dc69abb59ec277603e0a906952978bcab3d2470b65ffe97bcf49f248de58dbb21671d737f27b620d5acc75ca38e0459971",
          "sha256": "e527273b324534077fbfc5ceb594b168a42314f3ee9fbc3954d7dfca14338d86",
          "sha1": "0c4b35ca827242987f4c2e6c68e9936f24bb3f85",
          "md5": "ea369d891bf79de64f62d6c78bb77188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.1.jar",
          "url": "ftc-mocks-9.3.1.jar",
          "size": 157974,
          "sha512": "d03d07c1d6c060f1d22ee8bd489881dc69abb59ec277603e0a906952978bcab3d2470b65ffe97bcf49f248de58dbb21671d737f27b620d5acc75ca38e0459971",
          "sha256": "e527273b324534077fbfc5ceb594b168a42314f3ee9fbc3954d7dfca14338d86",
          "sha1": "0c4b35ca827242987f4c2e6c68e9936f24bb3f85",
          "md5": "ea369d891bf79de64f62d6c78bb77188"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-9.3.1-sources.jar",
          "url": "ftc-mocks-9.3.1-sources.jar",
          "size": 37765,
          "sha512": "c8c7a00097e70c6fc257cfc3b66e8779260e1d7e489ad196a5e643e021a8ba3d4368e4284c798474c6319caba452baff47245b9077917af0be874568f4aad84e",
          "sha256": "be6cb95374e14fe02cde3908a286c906ac2077750510c67c54f0d76552a0b799",
          "sha1": "a9f27bd05bac0cd17637d9be97b816180aaa55eb",
          "md5": "f679c713eed4b12645cd5e5f824c639c"
        }
      ]
    }
  ]
}
