{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.3.2.jar",
          "url": "simulator-runtime-linux-9.3.2.jar",
          "size": 4326,
          "sha512": "e7d6449e35f7f57dbfe4b667044444a3e4427b6035c7093bf91ea69e6d50c82849533cbe5a463844f536c5afc52ffa3ea8efa48f86124602179d26821693eec9",
          "sha256": "dff2ebdcf7c455bd1e8926b2eaaa44ddf9d584af02dc1b8d0fed6856cd210fc2",
          "sha1": "5e6a337ba5350d46654eb4f7835745d4d2206adf",
          "md5": "c6943632d35f7ff2a66a336be622d34a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-9.3.2.jar",
          "url": "simulator-runtime-linux-9.3.2.jar",
          "size": 4326,
          "sha512": "e7d6449e35f7f57dbfe4b667044444a3e4427b6035c7093bf91ea69e6d50c82849533cbe5a463844f536c5afc52ffa3ea8efa48f86124602179d26821693eec9",
          "sha256": "dff2ebdcf7c455bd1e8926b2eaaa44ddf9d584af02dc1b8d0fed6856cd210fc2",
          "sha1": "5e6a337ba5350d46654eb4f7835745d4d2206adf",
          "md5": "c6943632d35f7ff2a66a336be622d34a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-9.3.2-sources.jar",
          "url": "simulator-runtime-linux-9.3.2-sources.jar",
          "size": 4326,
          "sha512": "13d96ba887d569c465d6d5e08b562cf9d15068d3588a5ca1eb1bb5202e3aaeb385e4094fe78213bb386fbf9e539986ef501b3f734389f4bd224cbd635db0de13",
          "sha256": "e6d855084ca8ce23933148dbed161b88aaaa9999de52fa38d17153669369cbde",
          "sha1": "21ef479a9dc33f85b11e0c07319f658deb9646c3",
          "md5": "0b081b5baaacd7c930d1ce9d3fc8ff4c"
        }
      ]
    }
  ]
}
