{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.2.1.jar",
          "url": "codegen-9.2.1.jar",
          "size": 277470,
          "sha512": "4c08955b48eaddaf5a889c08ab2ac61aad77c484fae1e9149395f47102f4ff9f6586c78b6718e4dd67d66da071d9c8ec52fe99ec5045c72e1196cff72f2db404",
          "sha256": "4f3e7384a2631c624ec3a0a0c34f4600ffd7e3c116cf600b15bec3b45470d754",
          "sha1": "df42a89240117ce4c7776ee0d56e1484df2d63d0",
          "md5": "e2929586cdfd1edfb6ce741fc0d35d8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.2.1.jar",
          "url": "codegen-9.2.1.jar",
          "size": 277470,
          "sha512": "4c08955b48eaddaf5a889c08ab2ac61aad77c484fae1e9149395f47102f4ff9f6586c78b6718e4dd67d66da071d9c8ec52fe99ec5045c72e1196cff72f2db404",
          "sha256": "4f3e7384a2631c624ec3a0a0c34f4600ffd7e3c116cf600b15bec3b45470d754",
          "sha1": "df42a89240117ce4c7776ee0d56e1484df2d63d0",
          "md5": "e2929586cdfd1edfb6ce741fc0d35d8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-9.2.1-sources.jar",
          "url": "codegen-9.2.1-sources.jar",
          "size": 542591,
          "sha512": "d796a4f17859476755319683688d1a3eee8ff36a83c14e7a3fbc8cff452c6b9ec79f8d3e04f95e6e6cf8dbfaf4206d07c9f2bcb06b7e37db9a283d1c3534a1c9",
          "sha256": "af6af2f6ece45402aa365cf666b31d4788811577534ec2a64f4b88d4903752d1",
          "sha1": "815fad9788ca1b19509eeb2b9903c2359fc57e74",
          "md5": "bc9446b272a9c0a80e61d29dccefd3a7"
        }
      ]
    }
  ]
}
