{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulation-foundation",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "10.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-10.1.0.jar",
          "url": "simulation-foundation-10.1.0.jar",
          "size": 35282,
          "sha512": "7f2fcd6669d222961c2b9f58f985f738c5c689b098efdd768ef490d8c6313cf8914aeb0163bc23b405c1780070bbc8b0bfa2c63b55c183b525f3b14119e8d381",
          "sha256": "7b7704663dd78aa935d31f94ccfaecf3e3ae0940a1999bc0e0093a8616db56b4",
          "sha1": "3e993efc5f49875b592c083166634f636211a98c",
          "md5": "d9b41289d39d876b1636970afb395a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "10.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulation-foundation-10.1.0.jar",
          "url": "simulation-foundation-10.1.0.jar",
          "size": 35282,
          "sha512": "7f2fcd6669d222961c2b9f58f985f738c5c689b098efdd768ef490d8c6313cf8914aeb0163bc23b405c1780070bbc8b0bfa2c63b55c183b525f3b14119e8d381",
          "sha256": "7b7704663dd78aa935d31f94ccfaecf3e3ae0940a1999bc0e0093a8616db56b4",
          "sha1": "3e993efc5f49875b592c083166634f636211a98c",
          "md5": "d9b41289d39d876b1636970afb395a3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulation-foundation-10.1.0-sources.jar",
          "url": "simulation-foundation-10.1.0-sources.jar",
          "size": 8776,
          "sha512": "0ae6d14f89edd9e6c915ea829581231fca8bf018178e768af9b93923129e0067b591f8b2890ab59412c05be9b0b4f2d0e02587a77207ab1189644b45c8e69ee9",
          "sha256": "b32e124d2c0256bcce2c88e71071c120e39cc62480fab56aa2dc628e78297131",
          "sha1": "8a16151ea9560cf3d28bcbd7ccbde23c675f9612",
          "md5": "1daa060e4c17f2bc2622d9d51386a276"
        }
      ]
    }
  ]
}
