{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.11.0.jar",
          "url": "core-9.11.0.jar",
          "size": 2225386,
          "sha512": "2276befa405239bb64c96682d5e1eed748cbc69860263d88c3ed0a1d4edebe49af67c2a96d5d1e76193f16c7962973bf184383d7c53a5c34474b68b86561c92d",
          "sha256": "a7d70c294b587d5204d2fd0fa2577f78893d403b3ad8d303ed9fd931885cb7a6",
          "sha1": "55d2fb358bc25413631c2da0891d0e078f3cc9a3",
          "md5": "886e0269a509d5d3482999d3f0301550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.11.0.jar",
          "url": "core-9.11.0.jar",
          "size": 2225386,
          "sha512": "2276befa405239bb64c96682d5e1eed748cbc69860263d88c3ed0a1d4edebe49af67c2a96d5d1e76193f16c7962973bf184383d7c53a5c34474b68b86561c92d",
          "sha256": "a7d70c294b587d5204d2fd0fa2577f78893d403b3ad8d303ed9fd931885cb7a6",
          "sha1": "55d2fb358bc25413631c2da0891d0e078f3cc9a3",
          "md5": "886e0269a509d5d3482999d3f0301550"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-9.11.0-sources.jar",
          "url": "core-9.11.0-sources.jar",
          "size": 579803,
          "sha512": "6aa9da363c3f5ef3f619826fdf2744d84f3acb582846a3484546d88bc0cc84d0d1359374ca8f0f622e3d8fd58fa40646c44629deb4118a1df9f5755f089763f9",
          "sha256": "164d3716173dea52f06448e0b73d8a3bba366a8247420879d00b9ca0045593d8",
          "sha1": "571fa057e254d5e0fe4e07aaaab2914048444178",
          "md5": "28d26871bad42098cced5ad64b4f994c"
        }
      ]
    }
  ]
}
