{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "9.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.12.0.jar",
          "url": "codegen-9.12.0.jar",
          "size": 301673,
          "sha512": "08455b1766a3d9abeb5ad31ddb4d4429820f590678607626a68e9fea405f06f348b44dc18f648cf4357c4ec2ef8d912009e725f52fdf267c12dac3839ee04f1a",
          "sha256": "a437a59b7acc3d97594e9d8abc4b57501f0b57aec08d8cf4b492abfd64b1dc33",
          "sha1": "d010fbc812851c7d5764e311d82c2ca5b024f4ff",
          "md5": "0e6e934c5683e1b2d89190cfdf6aad50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.12.0.jar",
          "url": "codegen-9.12.0.jar",
          "size": 301673,
          "sha512": "08455b1766a3d9abeb5ad31ddb4d4429820f590678607626a68e9fea405f06f348b44dc18f648cf4357c4ec2ef8d912009e725f52fdf267c12dac3839ee04f1a",
          "sha256": "a437a59b7acc3d97594e9d8abc4b57501f0b57aec08d8cf4b492abfd64b1dc33",
          "sha1": "d010fbc812851c7d5764e311d82c2ca5b024f4ff",
          "md5": "0e6e934c5683e1b2d89190cfdf6aad50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-9.12.0-sources.jar",
          "url": "codegen-9.12.0-sources.jar",
          "size": 581524,
          "sha512": "b8fb09d8323165612666b1a46437e7b9ea38e06c2dd8e7f37a5135f417142322292a5ee5bfd5601811313310a299881bf1a17056df939dec9605603140cea84a",
          "sha256": "5ea46c002159b0f0236400c0af95f561efae2832355fc41a79ea7983ab9c78f5",
          "sha1": "e8ba86447706ccbc855c0aeae9f01b889ef66d6f",
          "md5": "b9911e871562892fe48d8bb547e39449"
        }
      ]
    }
  ]
}
