{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.3.1.jar",
          "url": "codegen-9.3.1.jar",
          "size": 277470,
          "sha512": "99976eb84901df462e93f621bd995b807e765f4f152b88201e0de82d0d58ea09bed2d3d4a224f18d0641d99b167e6e7e011c8ad29142cfb1d3e3ebcdee3bb30d",
          "sha256": "a0fab5ea860b35047835c750bf5ad1990d040a2673f23a59ca1a5f71f13b8a56",
          "sha1": "0b1054707eb6473566d133da8e3c1ca0ec96f89c",
          "md5": "c358f867232bdd19fa0ae06acf050e5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.3.1.jar",
          "url": "codegen-9.3.1.jar",
          "size": 277470,
          "sha512": "99976eb84901df462e93f621bd995b807e765f4f152b88201e0de82d0d58ea09bed2d3d4a224f18d0641d99b167e6e7e011c8ad29142cfb1d3e3ebcdee3bb30d",
          "sha256": "a0fab5ea860b35047835c750bf5ad1990d040a2673f23a59ca1a5f71f13b8a56",
          "sha1": "0b1054707eb6473566d133da8e3c1ca0ec96f89c",
          "md5": "c358f867232bdd19fa0ae06acf050e5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-9.3.1-sources.jar",
          "url": "codegen-9.3.1-sources.jar",
          "size": 546490,
          "sha512": "e5553f1738f2955f7988307a661836f82cc6610063f731c76b6c14294f3cd365c4d7e47e92a8b5c7c8ebcd493690d6acd4f067ae9c1c17bf12d6e2f30b76ed58",
          "sha256": "1dfe0bc0b2fce16a4cc9a46a111b6bea773f8cd88ac177d859c1b53c76e71ef9",
          "sha1": "aee031d75036bf51e73540e8b02bef732fbc5f47",
          "md5": "05fc1e138d0543e7c32d8bed91724aab"
        }
      ]
    }
  ]
}
