{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "codegen",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.3.1.jar",
          "url": "codegen-9.3.1.jar",
          "size": 277470,
          "sha512": "b8993eaec5c1b364f4dafa510f4663178f515f6c04201eaac62929347c7c833662b7e3a46b305139b6da38a9224375d8d691c8858dfc78e764381360a26c04bb",
          "sha256": "0a8ba3a1564efa5b338887650f609e65655346cc9fe89e3c4e6d7462eea4d1c9",
          "sha1": "6260a5ce806178b2cdf9cf2caae430fa9d71edce",
          "md5": "25c3e2999fc5693399cf2d9c1c25c3e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "codegen-9.3.1.jar",
          "url": "codegen-9.3.1.jar",
          "size": 277470,
          "sha512": "b8993eaec5c1b364f4dafa510f4663178f515f6c04201eaac62929347c7c833662b7e3a46b305139b6da38a9224375d8d691c8858dfc78e764381360a26c04bb",
          "sha256": "0a8ba3a1564efa5b338887650f609e65655346cc9fe89e3c4e6d7462eea4d1c9",
          "sha1": "6260a5ce806178b2cdf9cf2caae430fa9d71edce",
          "md5": "25c3e2999fc5693399cf2d9c1c25c3e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "codegen-9.3.1-sources.jar",
          "url": "codegen-9.3.1-sources.jar",
          "size": 546466,
          "sha512": "7f350cdcae6352396036beaa389b8a98c2b54f34eceb799708943188772d6063c289de8e128f240e20974188eee700bcb37c336052287967cf1cc9be8bbe9e5a",
          "sha256": "6678e3f6a7a928c138b3fe5acced1f53b35ae70694bc764d7dd332158877a4e8",
          "sha1": "8f8824a8402813567af63ba0a3b83e3d83838385",
          "md5": "c8c9c3b03fc5e1346c95596720e9150b"
        }
      ]
    }
  ]
}
