{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.2.jar",
          "url": "ftc-mocks-9.3.2.jar",
          "size": 157974,
          "sha512": "39f86d13c48ee76863eeeed6d86bd66244b40e3eda9a50dd5ec86affc159d3ba8a31f7b545ddad1621ce837feb5df89f7296fbd6e1a48d563bf19fd0fb1df4fb",
          "sha256": "7bba31826fc2774798f400a2fbfbb089c62fea4ebe78c605317fe67f1836b853",
          "sha1": "4a384512d2e325a452feb374d09ac9640388994b",
          "md5": "562bade30c2b036b45c1ac05a7fe9ad6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.3.2.jar",
          "url": "ftc-mocks-9.3.2.jar",
          "size": 157974,
          "sha512": "39f86d13c48ee76863eeeed6d86bd66244b40e3eda9a50dd5ec86affc159d3ba8a31f7b545ddad1621ce837feb5df89f7296fbd6e1a48d563bf19fd0fb1df4fb",
          "sha256": "7bba31826fc2774798f400a2fbfbb089c62fea4ebe78c605317fe67f1836b853",
          "sha1": "4a384512d2e325a452feb374d09ac9640388994b",
          "md5": "562bade30c2b036b45c1ac05a7fe9ad6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-9.3.2-sources.jar",
          "url": "ftc-mocks-9.3.2-sources.jar",
          "size": 37765,
          "sha512": "8b585e75fa796029c5e46bacedc1bae494076baf17c27203e83aa623acbaa745bab3b73f85f00b4ed182cad15c43d532d0d942fe44af96ccf0035f35accb7cce",
          "sha256": "ba33f005f64878cfe8808882bd77696cc08c354eddad9c2b9cf3865973a0a1e2",
          "sha1": "f9b10271c8a5dbe80ce285aefe4d43983fe6cd63",
          "md5": "21db5b288420ce87ac16b9fc3d7ca068"
        }
      ]
    }
  ]
}
