{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "9.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.7.0.jar",
          "url": "simulator-runtime-windows-9.7.0.jar",
          "size": 4326,
          "sha512": "6991d3fcb8048cbc25f6d960aa6dad3787d6ec83215e5f7c60a66dad2459fd1fa864064f407b5b91dccf92f1c2620e4afbf8b89cb487ab8e9d580ef0c90c4cc9",
          "sha256": "1b64e70db2ce07c1715e457c772112f9642e1cf793077561305080307ddae8ca",
          "sha1": "3a860eed6969b9a4f5f7e084d9091fc64e8b8ff5",
          "md5": "2814afd1b1c01eed3a958889ab78273e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.7.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.7.0.jar",
          "url": "simulator-runtime-windows-9.7.0.jar",
          "size": 4326,
          "sha512": "6991d3fcb8048cbc25f6d960aa6dad3787d6ec83215e5f7c60a66dad2459fd1fa864064f407b5b91dccf92f1c2620e4afbf8b89cb487ab8e9d580ef0c90c4cc9",
          "sha256": "1b64e70db2ce07c1715e457c772112f9642e1cf793077561305080307ddae8ca",
          "sha1": "3a860eed6969b9a4f5f7e084d9091fc64e8b8ff5",
          "md5": "2814afd1b1c01eed3a958889ab78273e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-9.7.0-sources.jar",
          "url": "simulator-runtime-windows-9.7.0-sources.jar",
          "size": 4326,
          "sha512": "63954864db58888f23e8384c28a7310dd88fe815fa8e55101acee8f2456e574884fd2782f5c13bd9177e563c36c9331e03f2ac38184d4f7683984c3193ad992c",
          "sha256": "23e576ebc17ad95df52b9dcba6ecb301c0ae0304f0629aa1394730ba77394b17",
          "sha1": "6f68d677feb512d57b103c1ee1986057a04fbc77",
          "md5": "cda4eaba1efb8dbb6e7c1f91895965b6"
        }
      ]
    }
  ]
}
