{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "9.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-9.6.0.jar",
          "url": "simulator-9.6.0.jar",
          "size": 193112,
          "sha512": "402dac46d377b72857032c8c81ce35e2caad3bcacbc50637b2558effb0dfbdd59b436f45f3ebb311073559d827614461691cfd71379df4d384bb4821fd815dfa",
          "sha256": "479292443b267be774d913dc4b9d856162a5b7f4c8b671624094765aa8458e8b",
          "sha1": "cd83e362b219a6350e61c923ec4b7b00fa9cd9ff",
          "md5": "c988bd2d506c596a2a96b7cca432c404"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "9.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-9.6.0.jar",
          "url": "simulator-9.6.0.jar",
          "size": 193112,
          "sha512": "402dac46d377b72857032c8c81ce35e2caad3bcacbc50637b2558effb0dfbdd59b436f45f3ebb311073559d827614461691cfd71379df4d384bb4821fd815dfa",
          "sha256": "479292443b267be774d913dc4b9d856162a5b7f4c8b671624094765aa8458e8b",
          "sha1": "cd83e362b219a6350e61c923ec4b7b00fa9cd9ff",
          "md5": "c988bd2d506c596a2a96b7cca432c404"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-9.6.0-sources.jar",
          "url": "simulator-9.6.0-sources.jar",
          "size": 67531,
          "sha512": "0b8d498b341c9676eb89f048309f53ff66fda2fb9dd9383324ff58290103cc9883edefaa905e12a0fac2a68adab245c87bae7db0c1109892cc997c7e7e21b757",
          "sha256": "a934b1400810072aabde612f762ebc7e66807cf2347e45be0c06e4ac7044760e",
          "sha1": "9bf98a2ccd79cd1aae6b747974028655de7408ac",
          "md5": "9fdd07400053767b7ecb15da31b67a7e"
        }
      ]
    }
  ]
}
