{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.9.0.jar",
          "url": "ftc-hardware-9.9.0.jar",
          "size": 380268,
          "sha512": "faf032210d77aa818d314c3d9f3f548c7256caa28eb69051b1628a10ecb3842a780110db596dad8ab82ea556bd1d7ecd678c8d8d6e61f8aa1d48ded34d77c91a",
          "sha256": "c9bc357052886fa11edd6a72deb152c87ec61ac8a226b0d4af83bacfad7cb9a2",
          "sha1": "0955c239b601364d8bce9449244ebddd1cfc6ea1",
          "md5": "2ca43e155d85b3b322ea31ae03b24fcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.9.0.jar",
          "url": "ftc-hardware-9.9.0.jar",
          "size": 380268,
          "sha512": "faf032210d77aa818d314c3d9f3f548c7256caa28eb69051b1628a10ecb3842a780110db596dad8ab82ea556bd1d7ecd678c8d8d6e61f8aa1d48ded34d77c91a",
          "sha256": "c9bc357052886fa11edd6a72deb152c87ec61ac8a226b0d4af83bacfad7cb9a2",
          "sha1": "0955c239b601364d8bce9449244ebddd1cfc6ea1",
          "md5": "2ca43e155d85b3b322ea31ae03b24fcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.9.0-sources.jar",
          "url": "ftc-hardware-9.9.0-sources.jar",
          "size": 149885,
          "sha512": "4e74d39be3a6cdfa7966de54416b89f36de54733bb7615ab8250907e5f54dc896cb61c0e61fca4748edb377b28884ac8c9c59cfd7aa57b82d8d5391e2e16455b",
          "sha256": "9b52e3576d5376e1689e4e2d657185f6709162922bb10b2a0dfc5af53d59c2ff",
          "sha1": "f6498adee91d04ea13730e02f1f61704ca8c44bd",
          "md5": "f9fc2c78ad63b24c57754df439d2142b"
        }
      ]
    }
  ]
}
