{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-mocks",
    "version": "9.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.6.0.jar",
          "url": "ftc-mocks-9.6.0.jar",
          "size": 157974,
          "sha512": "84799743fa550bbc5228a4bc94854d3ff39548f1f02ce86774bd5a20ddcf490e9d2407f18ee5751e9b5afcb174f64c626815be8e3b9db184323ea4c2980295cd",
          "sha256": "251efd5483c93bb4d4438591a004bb5c344964697f9347e4f669edca47cf2286",
          "sha1": "419f611f53c011a4f82505107c124b00dc1c6dec",
          "md5": "672f8b362223270eed24a4e944ea6347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-mocks-9.6.0.jar",
          "url": "ftc-mocks-9.6.0.jar",
          "size": 157974,
          "sha512": "84799743fa550bbc5228a4bc94854d3ff39548f1f02ce86774bd5a20ddcf490e9d2407f18ee5751e9b5afcb174f64c626815be8e3b9db184323ea4c2980295cd",
          "sha256": "251efd5483c93bb4d4438591a004bb5c344964697f9347e4f669edca47cf2286",
          "sha1": "419f611f53c011a4f82505107c124b00dc1c6dec",
          "md5": "672f8b362223270eed24a4e944ea6347"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-mocks-9.6.0-sources.jar",
          "url": "ftc-mocks-9.6.0-sources.jar",
          "size": 37765,
          "sha512": "cf60c2f8d6f5be7848245fca7b71dd311b0f4013360f23909eb9d087958b21686aa99a3b92a39355d356b9be61aaa99d1ec6ca48679890772d0885b55c26a326",
          "sha256": "f36bced6846479fec1fcc911c05b0399659fdb88fd217439d1b62f870e840645",
          "sha1": "73bd2f4aa94285d39d82ec1f99e3f6c9e93e907c",
          "md5": "3ac5d066f73b40c3ca67213ad56da3a2"
        }
      ]
    }
  ]
}
