{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-linux",
    "version": "10.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "10.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-10.0.0.jar",
          "url": "simulator-runtime-linux-10.0.0.jar",
          "size": 5085,
          "sha512": "8a8a0911970f7cca7be48b82111e032f75fc623143c85bea1ff1dd869c2169210e5ac9185be37967ea38d9cc0b7ee30a652a7dab0c7517ca503627111b2db0e4",
          "sha256": "6c2a4386511f912d7f97c237a5203e53a69ccdcd7973348fb836db7414219b93",
          "sha1": "86d22a18610a2f8074d7e0edc86cde396080956e",
          "md5": "a54e0aea6e6c90af3fd73ef8580a077c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "linuxx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-linux-10.0.0.jar",
          "url": "simulator-runtime-linux-10.0.0.jar",
          "size": 5085,
          "sha512": "8a8a0911970f7cca7be48b82111e032f75fc623143c85bea1ff1dd869c2169210e5ac9185be37967ea38d9cc0b7ee30a652a7dab0c7517ca503627111b2db0e4",
          "sha256": "6c2a4386511f912d7f97c237a5203e53a69ccdcd7973348fb836db7414219b93",
          "sha1": "86d22a18610a2f8074d7e0edc86cde396080956e",
          "md5": "a54e0aea6e6c90af3fd73ef8580a077c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-linux-10.0.0-sources.jar",
          "url": "simulator-runtime-linux-10.0.0-sources.jar",
          "size": 5085,
          "sha512": "8a8a0911970f7cca7be48b82111e032f75fc623143c85bea1ff1dd869c2169210e5ac9185be37967ea38d9cc0b7ee30a652a7dab0c7517ca503627111b2db0e4",
          "sha256": "6c2a4386511f912d7f97c237a5203e53a69ccdcd7973348fb836db7414219b93",
          "sha1": "86d22a18610a2f8074d7e0edc86cde396080956e",
          "md5": "a54e0aea6e6c90af3fd73ef8580a077c"
        }
      ]
    }
  ]
}
