{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "9.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.2.1.jar",
          "url": "simulator-runtime-windows-9.2.1.jar",
          "size": 4326,
          "sha512": "7c484796d13f870b40ddb675d7f71e6d39b5832554005f10ef87b8392a76354c33e467dd1ba0cba75d8a3a1554e30d34f95b7b0431539383ad93f92f32db727e",
          "sha256": "00b66e02768e1162ecc907c9dc671b679fc1d772c505e4f1432df3996d9baa79",
          "sha1": "2fb81a021c029e5c793e383e96ced5caf9c4e240",
          "md5": "bf68859daec926893e4bf7e64fedd3d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.2.1.jar",
          "url": "simulator-runtime-windows-9.2.1.jar",
          "size": 4326,
          "sha512": "7c484796d13f870b40ddb675d7f71e6d39b5832554005f10ef87b8392a76354c33e467dd1ba0cba75d8a3a1554e30d34f95b7b0431539383ad93f92f32db727e",
          "sha256": "00b66e02768e1162ecc907c9dc671b679fc1d772c505e4f1432df3996d9baa79",
          "sha1": "2fb81a021c029e5c793e383e96ced5caf9c4e240",
          "md5": "bf68859daec926893e4bf7e64fedd3d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-9.2.1-sources.jar",
          "url": "simulator-runtime-windows-9.2.1-sources.jar",
          "size": 4326,
          "sha512": "7a57dacfc7963fa7100c9fbc7429608a30670cbe6f814cbeccee69454aeed8e26eb5ca5ca47d670baf7c3acdf5ee98f52d38c8d6807ef076a13ff77e6e1105fd",
          "sha256": "b4a2df40c13ebd7d547b71b30ade61d7f21939ed633f77c756be5e10a94a9831",
          "sha1": "a287bd5f04d6e8881087e33298e0c47a7c5c864b",
          "md5": "949e7af082c8e274ca7fd393923e86a5"
        }
      ]
    }
  ]
}
