{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.11.0.jar",
          "url": "ftc-hardware-9.11.0.jar",
          "size": 380268,
          "sha512": "10bd2a362f38ab66ac758e9cf935d33302fd5ac1920c7680fbd7b9cdb57b6b0219a42a025f79f2acc264bdc5a4a11bf354331b34f211a84f3a8256413b1843af",
          "sha256": "4df3d23db87731e47aca41d948678ea6fb4ae91e43e1c5c10bafd168e45bae5b",
          "sha1": "c25411e844f5d0151bb84f6c6223bf12640826e6",
          "md5": "ec7c939d6f5b2eb5eea8f70e5a506357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.11.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.11.0.jar",
          "url": "ftc-hardware-9.11.0.jar",
          "size": 380268,
          "sha512": "10bd2a362f38ab66ac758e9cf935d33302fd5ac1920c7680fbd7b9cdb57b6b0219a42a025f79f2acc264bdc5a4a11bf354331b34f211a84f3a8256413b1843af",
          "sha256": "4df3d23db87731e47aca41d948678ea6fb4ae91e43e1c5c10bafd168e45bae5b",
          "sha1": "c25411e844f5d0151bb84f6c6223bf12640826e6",
          "md5": "ec7c939d6f5b2eb5eea8f70e5a506357"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.11.0-sources.jar",
          "url": "ftc-hardware-9.11.0-sources.jar",
          "size": 149885,
          "sha512": "2fc0baae69f6a57b9b7a33e6204b1d5ee53517ae18d68f90494c0034e7c3aa1542bdb9abfda874d83883ec0937585606a2bc6ac26a147d70072a8f2cd6bbab07",
          "sha256": "f4435dde3eb1a570948e9dc3b36f866207588b545aa8e53ce57a376bdb52d47d",
          "sha1": "9578b1e458e47c45c0b10247554bb92395ad56ab",
          "md5": "1f8bf0b5f4c0111fcf3e95e665461db3"
        }
      ]
    }
  ]
}
