{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "10.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-10.0.0.jar",
          "url": "simulator-10.0.0.jar",
          "size": 200262,
          "sha512": "af7b1fa97bd7c291f8d587043e09dd8dac37f946c4c913b1937510f6c6b3ac9105391238afc2517cc84c93d99354ad2d6754e4e4bd2b295219200bc69055353c",
          "sha256": "0ab3d30590d9b2679233f214645704e42e83e65cb35af0c2c93b6aa22569e1a3",
          "sha1": "c543c0bd79754e232d7bce0853ff610ae1a5835f",
          "md5": "ee93cbdd1c3dbd60d014554a6b01aa6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-10.0.0.jar",
          "url": "simulator-10.0.0.jar",
          "size": 200262,
          "sha512": "af7b1fa97bd7c291f8d587043e09dd8dac37f946c4c913b1937510f6c6b3ac9105391238afc2517cc84c93d99354ad2d6754e4e4bd2b295219200bc69055353c",
          "sha256": "0ab3d30590d9b2679233f214645704e42e83e65cb35af0c2c93b6aa22569e1a3",
          "sha1": "c543c0bd79754e232d7bce0853ff610ae1a5835f",
          "md5": "ee93cbdd1c3dbd60d014554a6b01aa6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-10.0.0-sources.jar",
          "url": "simulator-10.0.0-sources.jar",
          "size": 71130,
          "sha512": "7d816a892e7811d3743a479fc0ec329a28392b6dc74957954525fed5dff22f6493d465d1ce7633307384a60871a8d66bc6981d1f457ade960f27e79155cd6629",
          "sha256": "21851887ce66cf76ad0f1fcb2db0b10189e1efffbaf34657c8852c4a647051e1",
          "sha1": "a5c3d792153c525e6b547f1e9ea3b26cec2c67e1",
          "md5": "0a2421ab61b71d06cfcfa13c975bca80"
        }
      ]
    }
  ]
}
