{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.3.1.jar",
          "url": "core-9.3.1.jar",
          "size": 2099084,
          "sha512": "0d78b397cd60c2885245cf509dabb628906a0514c3439334762b405d8033c9105042684ab1734fd7579c2904a5d897f8688df82f8fa4ff701f5e80cf69124dac",
          "sha256": "6e88ae8168ea098088154b86cfad2f65688d4ae7cf3a0fb7dd77b272f354325c",
          "sha1": "474f5b68d5ccf5588dd5949034238a00d187d3be",
          "md5": "a8f2bd4cabaa052d6d0a0275c4724e04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-9.3.1.jar",
          "url": "core-9.3.1.jar",
          "size": 2099084,
          "sha512": "0d78b397cd60c2885245cf509dabb628906a0514c3439334762b405d8033c9105042684ab1734fd7579c2904a5d897f8688df82f8fa4ff701f5e80cf69124dac",
          "sha256": "6e88ae8168ea098088154b86cfad2f65688d4ae7cf3a0fb7dd77b272f354325c",
          "sha1": "474f5b68d5ccf5588dd5949034238a00d187d3be",
          "md5": "a8f2bd4cabaa052d6d0a0275c4724e04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-9.3.1-sources.jar",
          "url": "core-9.3.1-sources.jar",
          "size": 546816,
          "sha512": "173a2f2923faca0d3f20fbae5f25e43fb0e9e64c23cb827436730fd00dfd91c1267af116487102b3864ad04576d7301f6304c57cca19512d80b94ff7a3f821a1",
          "sha256": "850fd1014774155e490df1fdeff16bda77b0926ddf6c8a3392309006e5ac5325",
          "sha1": "2e7d32f530c92b545f91b2ee8dd8a4c0eeb0f985",
          "md5": "b92c370030ce3bcd680be4dae0c0ef18"
        }
      ]
    }
  ]
}
