package com.areslib.pathing

import java.io.File
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.IOException
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import com.areslib.math.geometry.Pose2d
import com.areslib.math.geometry.Rotation2d

/**
 * Class implementation for Field Waypoint.
 *
 * Autonomous path planning, trajectory generation, and obstacle avoidance module.
 *
 * ### Coordinate System:
 * Field-centric coordinates in meters ($m$) relative to field origin.
 */
data class FieldWaypoint(
    val id: String,
    val name: String,
    val x: Double,
    val y: Double,
    val headingDegrees: Double,
    val locked: Boolean = false
) {
    /**
     * toPose declaration.
     * Provides high-performance, Zero-GC operations.
     * CCW-positive heading standard applied. 
     * Note: Physical units use standard SI metrics.
     * Uses LaTeX math representation for kinematics where applicable.
     *
     * @param args Standard arguments (if applicable).
     * @return Corresponding output value or Unit.
     */
    fun toPose(): Pose2d {
        return Pose2d(x, y, Rotation2d(Math.toRadians(headingDegrees)))
    }
}

/**
 * Dynamically resolves and loads field waypoints from field_waypoints.json
 * generated by the dashboard Field Editor.
 */
object FieldWaypointLoader {
    private val SEARCH_PATHS = listOf(
        "/sdcard/FIRST/tuning/paths",
        "/sdcard/FIRST/paths",
        "src/main/deploy/paths",
        "deploy/paths",
        "src/main/resources/deploy/paths",
        "../deploy/paths",
        "../../deploy/paths",
        "src/main/assets/paths",
        "TeamCode/src/main/assets/paths",
        "../TeamCode/src/main/assets/paths",
        "../../TeamCode/src/main/assets/paths"
    )

    private val gson = Gson()
    private val waypointListType = object : TypeToken<List<FieldWaypoint>>() {}.type
    private var cachedWaypoints: Map<String, FieldWaypoint>? = null

    /**
     * loadAllWaypoints declaration.
     * Provides high-performance, Zero-GC operations.
     * CCW-positive heading standard applied. 
     * Note: Physical units use standard SI metrics.
     * Uses LaTeX math representation for kinematics where applicable.
     *
     * @param args Standard arguments (if applicable).
     * @return Corresponding output value or Unit.
     */
    fun loadAllWaypoints(): Map<String, FieldWaypoint> {
        if (cachedWaypoints != null) return cachedWaypoints!!

        var jsonString: String? = null
        val fileName = "field_waypoints.json"

        // 1. Filesystem search
        for (dirPath in SEARCH_PATHS) {
            val file = File(dirPath, fileName)
            if (file.exists() && file.isFile) {
                try {
                    jsonString = file.readText(Charsets.UTF_8)
                    break
                } catch (e: Exception) {
                    System.err.println("WARN: Failed to read field waypoints at ${file.absolutePath}: ${e.message}")
                }
            }
        }

        // 2. Classpath search
        if (jsonString == null) {
            val classpathCandidates = listOf(
                "/deploy/paths/$fileName",
                "deploy/paths/$fileName",
                "/assets/paths/$fileName",
                "assets/paths/$fileName"
            )
            for (resourcePath in classpathCandidates) {
                try {
                    val stream = FieldWaypointLoader::class.java.getResourceAsStream(resourcePath)
                    if (stream != null) {
                        BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).use { reader ->
                            jsonString = reader.readText()
                        }
                        break
                    }
                } catch (e: Exception) {
                    // Ignore and try next resource path
                }
            }
        }

        if (jsonString == null) {
            System.err.println("WARN: field_waypoints.json not found in any standard directory or classpath.")
            return emptyMap()
        }

        return try {
            val list: List<FieldWaypoint> = gson.fromJson(jsonString, waypointListType)
            val map = list.associateBy { it.name }
            cachedWaypoints = map
            map
        } catch (e: Exception) {
            System.err.println("ERROR: Failed to parse field_waypoints.json: ${e.message}")
            emptyMap()
        }
    }

    /**
     * getWaypoint declaration.
     * Provides high-performance, Zero-GC operations.
     * CCW-positive heading standard applied. 
     * Note: Physical units use standard SI metrics.
     * Uses LaTeX math representation for kinematics where applicable.
     *
     * @param args Standard arguments (if applicable).
     * @return Corresponding output value or Unit.
     */
    fun getWaypoint(name: String): FieldWaypoint? {
        return loadAllWaypoints()[name]
    }

    /**
     * clearCache declaration.
     * Provides high-performance, Zero-GC operations.
     * CCW-positive heading standard applied. 
     * Note: Physical units use standard SI metrics.
     * Uses LaTeX math representation for kinematics where applicable.
     *
     * @param args Standard arguments (if applicable).
     * @return Corresponding output value or Unit.
     */
    fun clearCache() {
        cachedWaypoints = null
    }
}
