{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "11.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-11.0.0.jar",
          "url": "simulator-runtime-windows-11.0.0.jar",
          "size": 5100,
          "sha512": "32f4d101490e12f5e1f2329eb1d06bdf36ee56b878aec015912c927831c301d7df84ca41909b34641a6229ed7be7f57474271a520315e6c1428dcf3d53ce190a",
          "sha256": "eaf27c94a1f18daa1aae9a500ec779bc3b0d95cb7cb605d04a0cfe80b96fc1c8",
          "sha1": "690ac1f484f0a18c7bc357d3a3c57420874665c7",
          "md5": "cd055b11c5fadc0795e692c34878f324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-11.0.0.jar",
          "url": "simulator-runtime-windows-11.0.0.jar",
          "size": 5100,
          "sha512": "32f4d101490e12f5e1f2329eb1d06bdf36ee56b878aec015912c927831c301d7df84ca41909b34641a6229ed7be7f57474271a520315e6c1428dcf3d53ce190a",
          "sha256": "eaf27c94a1f18daa1aae9a500ec779bc3b0d95cb7cb605d04a0cfe80b96fc1c8",
          "sha1": "690ac1f484f0a18c7bc357d3a3c57420874665c7",
          "md5": "cd055b11c5fadc0795e692c34878f324"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-11.0.0-sources.jar",
          "url": "simulator-runtime-windows-11.0.0-sources.jar",
          "size": 5100,
          "sha512": "32f4d101490e12f5e1f2329eb1d06bdf36ee56b878aec015912c927831c301d7df84ca41909b34641a6229ed7be7f57474271a520315e6c1428dcf3d53ce190a",
          "sha256": "eaf27c94a1f18daa1aae9a500ec779bc3b0d95cb7cb605d04a0cfe80b96fc1c8",
          "sha1": "690ac1f484f0a18c7bc357d3a3c57420874665c7",
          "md5": "cd055b11c5fadc0795e692c34878f324"
        }
      ]
    }
  ]
}
