{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "core",
    "version": "11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-11.0.0.jar",
          "url": "core-11.0.0.jar",
          "size": 1624351,
          "sha512": "c4ba7dc0cc0301cfdd2488047f315c58a5f828ae8549d73cb778fbb0ab47705767b08fd96eff9ede4ea8dc18ddbed1a843b5d8fdcc223378ddcbdea4edf2e003",
          "sha256": "21208a05198b30da82ba976e6d4f85e1d3a7e8942985c55a1307da60c57c9796",
          "sha1": "749fcdcfc2914af89db7617215ad5c3f04f25fe0",
          "md5": "4465677cbf04e005369b45b6a2d20f35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "telemetry-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "project-schema",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-11.0.0.jar",
          "url": "core-11.0.0.jar",
          "size": 1624351,
          "sha512": "c4ba7dc0cc0301cfdd2488047f315c58a5f828ae8549d73cb778fbb0ab47705767b08fd96eff9ede4ea8dc18ddbed1a843b5d8fdcc223378ddcbdea4edf2e003",
          "sha256": "21208a05198b30da82ba976e6d4f85e1d3a7e8942985c55a1307da60c57c9796",
          "sha1": "749fcdcfc2914af89db7617215ad5c3f04f25fe0",
          "md5": "4465677cbf04e005369b45b6a2d20f35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-11.0.0-sources.jar",
          "url": "core-11.0.0-sources.jar",
          "size": 449404,
          "sha512": "b145efddd3ce36a68c72886c5314db36f504ea24ddc9f12ed9f4a42b27b932be9ea96c03bf77936a2bbc599db25860cc76d92b4809ce9d2a69ef7b35099d870c",
          "sha256": "7ff7111caed9c4a97e26df3d3822cf9a6ed6d359ddd25ac309eac059fa428fb5",
          "sha1": "1d1e6f4e1cb6b439b84c4f1df5f781e55b716ec9",
          "md5": "7e2e525f7a73ac5594c9ecd6baf030b2"
        }
      ]
    }
  ]
}
