{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator-runtime-windows",
    "version": "9.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.3.5.jar",
          "url": "simulator-runtime-windows-9.3.5.jar",
          "size": 4326,
          "sha512": "1698413dbe86474ed0b06726d985472cf06e6e62f599b39e7fe6b61a5b4058c8726053c591d588257687ca18b827fefbabd62afb3b108c87b80fbcd43af205f8",
          "sha256": "956e9d08f7ce56250f41484d2465a6bfc050ff0e9d72c4e95285d2b207643d92",
          "sha1": "eb14772069447ad63dde4e665c00de41001ee76e",
          "md5": "e472a97d940f3f882d8cafe45807f0b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "simulator",
          "version": {
            "requires": "9.3.5"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpinet-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ntcore-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpiutil-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "wpimath-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-jni",
          "version": {
            "requires": "2024.3.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "hal-jni",
              "type": "jar",
              "extension": "jar",
              "classifier": "windowsx86-64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.3.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-glfw",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-runtime-windows-9.3.5.jar",
          "url": "simulator-runtime-windows-9.3.5.jar",
          "size": 4326,
          "sha512": "1698413dbe86474ed0b06726d985472cf06e6e62f599b39e7fe6b61a5b4058c8726053c591d588257687ca18b827fefbabd62afb3b108c87b80fbcd43af205f8",
          "sha256": "956e9d08f7ce56250f41484d2465a6bfc050ff0e9d72c4e95285d2b207643d92",
          "sha1": "eb14772069447ad63dde4e665c00de41001ee76e",
          "md5": "e472a97d940f3f882d8cafe45807f0b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-runtime-windows-9.3.5-sources.jar",
          "url": "simulator-runtime-windows-9.3.5-sources.jar",
          "size": 4326,
          "sha512": "96bccb23ae1020127037eb4e2ea12dfcfe877241891ee31bb81120367d3fc7f337e04845fb749c6b5540226575c2460c882495d889f9c89ae60224b424bdb353",
          "sha256": "55c21f3c4d58c6774622632c04b96036112e90477c0c8afa3b24ae7f92ecabd7",
          "sha1": "432656e1a915e82dea4ac0e5129cdfd6ed1bca9a",
          "md5": "99b683eac120de9898e59355492690af"
        }
      ]
    }
  ]
}
