{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "simulator",
    "version": "10.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-10.1.0.jar",
          "url": "simulator-10.1.0.jar",
          "size": 200262,
          "sha512": "4d427bd6d3cd9afbae4e4ed4aad4cab2a981057f9b93cdaaebdfe33f08ba2a1d8fd6dc3dc7ae622f7ba87967c0946aa7a0a944d7084eb8447ec82068fc34e078",
          "sha256": "7bd75cdfdf335a9fa81827eb4d754a694418fea844d1315a00aa9c7460b3c551",
          "sha1": "b5b17d266f8b79bc210ba2037f6b8e3780ba7ecb",
          "md5": "d3efb942762114d615c21040d7fc3813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.18"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-hardware",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "ftc-mocks",
          "version": {
            "requires": "10.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-10.1.0.jar",
          "url": "simulator-10.1.0.jar",
          "size": 200262,
          "sha512": "4d427bd6d3cd9afbae4e4ed4aad4cab2a981057f9b93cdaaebdfe33f08ba2a1d8fd6dc3dc7ae622f7ba87967c0946aa7a0a944d7084eb8447ec82068fc34e078",
          "sha256": "7bd75cdfdf335a9fa81827eb4d754a694418fea844d1315a00aa9c7460b3c551",
          "sha1": "b5b17d266f8b79bc210ba2037f6b8e3780ba7ecb",
          "md5": "d3efb942762114d615c21040d7fc3813"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "simulator-10.1.0-sources.jar",
          "url": "simulator-10.1.0-sources.jar",
          "size": 71130,
          "sha512": "bbe5e37ec5e283cb7f802077828af304ba91dbdb0157453d99f9cb867eaa6daa530d5ed803a0179d29e715a2130c3f2c7cfedf1eea011db4342aaf889dd95a5e",
          "sha256": "a31962c870924f90e4a91ad324d110c4b4e87ba9cb414aa71395d484eb7c8bb3",
          "sha1": "4900070bca2e54ce360449617a6475ad09d2452f",
          "md5": "c04468d7ad610fc9bc79117c092b7d9c"
        }
      ]
    }
  ]
}
