package com.areslib.frc

import com.areslib.state.DriveState
import com.areslib.state.RobotState
import com.areslib.reducer.rootReducer
import edu.wpi.first.wpilibj.TimedRobot
import edu.wpi.first.wpilibj.XboxController
import edu.wpi.first.wpilibj.RobotController

import org.dyn4j.dynamics.Body
import org.dyn4j.world.World
import org.dyn4j.geometry.Geometry
import org.dyn4j.geometry.MassType

/**
 * Main Robot loop for the FRC CTRE Swerve Integration.
 * Replaces the traditional command-based FRC robot with the pure mathematical Redux state machine.
 */
class ARESRobot : TimedRobot() {

    // Redux State
    private var currentState = RobotState(
        drive = DriveState(
            odometryX = 2.0, 
            odometryY = 2.0, 
            odometryHeading = 0.0
        )
    )
    
    // Telemetry and Logging
    private val telemetry = FRCTelemetry()
    
    // Virtual/Physical Gamepad
    private val driverController = XboxController(0)
    
    // Hardware IO Bridge
    // NOTE: In a real project, this would be the CommandSwerveDrivetrain generated by Phoenix Tuner X.
    // private lateinit var swerveIO: FRCSwerveHardwareIO<*>

    // Dyn4j Physics
    private val world = World<Body>()
    private val robotBody = Body()
    private val balls = mutableListOf<Body>()

    override fun robotInit() {
        // Initialize CTRE SwerveDrivetrain here using TunerConstants
        // swerveIO = FRCSwerveHardwareIO(CommandSwerveDrivetrain(...))
        
        world.setGravity(org.dyn4j.geometry.Vector2(0.0, 0.0))
        
        // Robot Setup
        val robotFixture = robotBody.addFixture(Geometry.createRectangle(0.7, 0.7)) // ~28 inch square
        robotFixture.density = 78.0
        robotBody.setMass(MassType.NORMAL)
        robotBody.translate(2.0, 2.0)
        world.addBody(robotBody)
        
        createWalls()
        spawnFuel()
    }

    override fun robotPeriodic() {
        // 1. READ (Hardware -> State)
        val timestamp = System.currentTimeMillis()
        
        // val driveState = swerveIO.read()
        val driveState = currentState.drive // Use previous state so odometry doesn't reset to 0.0
        
        // 2. STATE MERGE (Hardware -> State)
        currentState = currentState.copy(
            timestampMs = timestamp,
            drive = driveState
        )
        
        // In teleop, we would map the XboxController to ChassisSpeeds or commands here.
        if (isTeleop) {
            // Apply deadbands so it doesn't drift
            val applyDeadband = { value: Double -> if (Math.abs(value) < 0.1) 0.0 else value }
            val forward = applyDeadband(-driverController.leftY)
            val strafe = applyDeadband(-driverController.leftX)
            val rotation = applyDeadband(-driverController.rightX)
            
            val vx = forward * 4.5
            val vy = strafe * 4.5
            val omega = rotation * Math.PI
            
            // For example, mapping to DriveState velocities (Placeholder math)
            currentState = currentState.copy(
                drive = currentState.drive.copy(
                    xVelocityMetersPerSecond = vx,
                    yVelocityMetersPerSecond = vy,
                    angularVelocityRadiansPerSecond = omega
                )
            )
        }
        
        // 3. WRITE (State -> Hardware)
        // swerveIO.write(currentState.drive)
        
        // 4. TELEMETRY (Log deterministic state)
        telemetry.putNumber("Robot/Odometry/X", currentState.drive.odometryX)
        telemetry.putNumber("Robot/Odometry/Y", currentState.drive.odometryY)
        telemetry.putNumber("Robot/Odometry/Heading", currentState.drive.odometryHeading)
        telemetry.putDoubleArray("Robot/Pose", doubleArrayOf(
            currentState.drive.odometryX, 
            currentState.drive.odometryY, 
            currentState.drive.odometryHeading
        ))
    }

    override fun simulationPeriodic() {
        // Step Dyn4j Physics Engine
        val kpLinear = 50.0
        val kpAngular = 20.0
        val forceX = (currentState.drive.xVelocityMetersPerSecond - robotBody.linearVelocity.x) * kpLinear
        val forceY = (currentState.drive.yVelocityMetersPerSecond - robotBody.linearVelocity.y) * kpLinear
        val torque = (currentState.drive.angularVelocityRadiansPerSecond - robotBody.angularVelocity) * kpAngular

        robotBody.isAtRest = false
        robotBody.applyForce(org.dyn4j.geometry.Vector2(forceX, forceY))
        robotBody.applyTorque(torque)
        
        world.step(1, 0.02)

        // Read back the pose from physics
        val t = robotBody.transform
        currentState = currentState.copy(
            drive = currentState.drive.copy(
                odometryX = t.translationX,
                odometryY = t.translationY,
                odometryHeading = t.rotationAngle
            )
        )
        
        // Publish Fuel 3D Array
        val gamePieceData = DoubleArray(balls.size * 7)
        for (i in balls.indices) {
            gamePieceData[i * 7] = balls[i].transform.translationX
            gamePieceData[i * 7 + 1] = balls[i].transform.translationY
            gamePieceData[i * 7 + 2] = 0.0635 // Z height (radius)
            
            val theta = balls[i].transform.rotationAngle
            gamePieceData[i * 7 + 3] = kotlin.math.cos(theta / 2.0) // qW
            gamePieceData[i * 7 + 4] = 0.0                          // qX
            gamePieceData[i * 7 + 5] = 0.0                          // qY
            gamePieceData[i * 7 + 6] = kotlin.math.sin(theta / 2.0) // qZ
        }
        telemetry.putDoubleArray("Robot/FuelPoses", gamePieceData)
    }
    
    private fun createWalls() {
        val width = 16.541
        val height = 8.069
        
        // 4 outer walls
        val top = Body()
        top.addFixture(Geometry.createRectangle(width, 0.1))
        top.setMass(MassType.INFINITE)
        top.translate(width / 2.0, height)
        world.addBody(top)
        
        val bottom = Body()
        bottom.addFixture(Geometry.createRectangle(width, 0.1))
        bottom.setMass(MassType.INFINITE)
        bottom.translate(width / 2.0, 0.0)
        world.addBody(bottom)
        
        val left = Body()
        left.addFixture(Geometry.createRectangle(0.1, height))
        left.setMass(MassType.INFINITE)
        left.translate(0.0, height / 2.0)
        world.addBody(left)
        
        val right = Body()
        right.addFixture(Geometry.createRectangle(0.1, height))
        right.setMass(MassType.INFINITE)
        right.translate(width, height / 2.0)
        world.addBody(right)
        
        // Blue Hub
        val blueHub = Body()
        blueHub.addFixture(Geometry.createRectangle(1.1938, 1.1938))
        blueHub.setMass(MassType.INFINITE)
        blueHub.translate(4.135, 4.0345)
        world.addBody(blueHub)
        
        // Red Hub
        val redHub = Body()
        redHub.addFixture(Geometry.createRectangle(1.1938, 1.1938))
        redHub.setMass(MassType.INFINITE)
        redHub.translate(16.541 - 4.135, 4.0345)
        world.addBody(redHub)
    }

    private fun spawnFuel() {
        val random = java.util.Random()
        for (i in 0 until 100) {
            val ball = Body()
            val fixture = ball.addFixture(Geometry.createCircle(0.0635)) // 5 inch diameter
            fixture.friction = 0.6
            fixture.restitution = 0.4
            fixture.density = 5.92
            ball.setMass(MassType.NORMAL)
            ball.linearDamping = 2.0
            ball.angularDamping = 2.0
            
            // Random position inside the field walls, avoiding walls and hubs
            val x = 1.0 + random.nextDouble() * 14.0
            val y = 1.0 + random.nextDouble() * 6.0
            ball.translate(x, y)
            world.addBody(ball)
            balls.add(ball)
        }
    }
}
