{
  "formatVersion": "1.1",
  "component": {
    "group": "org.aresfirst.ares",
    "module": "ftc-hardware",
    "version": "9.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.8.0.jar",
          "url": "ftc-hardware-9.8.0.jar",
          "size": 380268,
          "sha512": "c59536f2954e836cff0647bf0a8448a552776d5466840fb925ce1efa62c05e8821d9ed0d4c14d5ada318b73416a62ca1fc195d19ee4bf5808a53e77112a6cd2d",
          "sha256": "9d584f1fd983fc5364f97ee61567295e6305f7c5f47b2e5d1dec09e8651ffe84",
          "sha1": "c968b9213f17c167384318c1e8d8a416b2daf309",
          "md5": "0589906fa741e2186842f0d383fc7d1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.aresfirst.ares",
          "module": "core",
          "version": {
            "requires": "9.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-hardware-9.8.0.jar",
          "url": "ftc-hardware-9.8.0.jar",
          "size": 380268,
          "sha512": "c59536f2954e836cff0647bf0a8448a552776d5466840fb925ce1efa62c05e8821d9ed0d4c14d5ada318b73416a62ca1fc195d19ee4bf5808a53e77112a6cd2d",
          "sha256": "9d584f1fd983fc5364f97ee61567295e6305f7c5f47b2e5d1dec09e8651ffe84",
          "sha1": "c968b9213f17c167384318c1e8d8a416b2daf309",
          "md5": "0589906fa741e2186842f0d383fc7d1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-hardware-9.8.0-sources.jar",
          "url": "ftc-hardware-9.8.0-sources.jar",
          "size": 149885,
          "sha512": "47491f23b98e4b75d4e3f03b806148d03a2fd3c7c5b75e1fab179a01b817bbb3873e290ff343d920f42b07952c1d90e3badd5dc7118480b2e61b6060f549c81f",
          "sha256": "7709a93426ee2d327af4bbb27cef47ac3549e4e2cb155df8da0a8181c6680f40",
          "sha1": "dad773f770153b3de68738b6e8f4abb392658660",
          "md5": "5fdeefe0a7c981d32d9a5867182454dd"
        }
      ]
    }
  ]
}
